// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCET-bQ0ZgBZmkLYOawZSKOal7IdxJ3vpY',
    appId: '1:108745405096:web:38d6d70d59a211b94d489d',
    messagingSenderId: '108745405096',
    projectId: 'task1-acebb',
    authDomain: 'task1-acebb.firebaseapp.com',
    storageBucket: 'task1-acebb.appspot.com',
    measurementId: 'G-5C41DYXK9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_CDEqMpcMiOuNKc_lWcxKdTMBXuDf-3c',
    appId: '1:108745405096:android:ac6173d3b65d89624d489d',
    messagingSenderId: '108745405096',
    projectId: 'task1-acebb',
    storageBucket: 'task1-acebb.appspot.com',
  );
}
